# ████████╗███╗   ███╗██╗   ██╗██╗  ██╗
# ╚══██╔══╝████╗ ████║██║   ██║╚██╗██╔╝
#    ██║   ██╔████╔██║██║   ██║ ╚███╔╝
#    ██║   ██║╚██╔╝██║██║   ██║ ██╔██╗
#    ██║   ██║ ╚═╝ ██║╚██████╔╝██╔╝ ██╗
#    ╚═╝   ╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═╝

# action key
unbind C-b
set-option -g prefix C-t
set-option -g repeat-time 0
set-option -g allow-rename off
set-option -g focus-events on
set-option -g display-time 3000

# colors
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"

set -g base-index 1          # start indexing windows at 1 instead of 0
set -g detach-on-destroy off # don't exit from tmux when closing a session
set -g escape-time 0         # zero-out escape time delay
set -g history-limit 5000    # increase history size (from 2,000)
set -g mouse on              # enable mouse support
set -g renumber-windows on   # renumber all windows when any window is closed
set -g set-clipboard on      # use system clipboard
set -g status-interval 120   # update the status bar every 120 seconds

set -g message-command-style bg=default,fg=black
set -g mode-style bg=default,fg=yellow
set -g pane-active-border-style 'fg=blue,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

# Prevent Ctrl + Enter does not work in `opencode`
set -g extended-keys always
unbind C-Enter

# reload configuration
bind r source-file ~/.tmux.conf \; display-message "󰑓 Config reloaded"

# maximize and minimize pane
bind -r "m" resize-pane -Z

# setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection

# use \ to create a vertical pane & start in current dir
unbind "%"
bind "\\" split-window -h -c "#{pane_current_path}"

# use \ to create a horizontal pane & start in current dir
unbind '"'
bind "-" split-window -v -c "#{pane_current_path}"
bind e set -g synchronize-panes

bind c   new-window   -c '#{pane_current_path}'
bind h   select-pane  -L
bind j   select-pane  -D
bind k   select-pane  -U
bind l   select-pane  -R

# Equally resize all panes
bind-key = select-layout even-horizontal
bind-key | select-layout even-vertical

# Resize panes
bind-key J resize-pane -D 10
bind-key K resize-pane -U 10
bind-key H resize-pane -L 10
bind-key L resize-pane -R 10

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Enabled vi keybinding
setw -g mode-keys vi
set -g mode-style "fg=default,bg=default,reverse"

bind-key -T copy-mode-vi 'v'   send-keys -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

set -g status-position top
source-file ~/.config/tmux/themes/dank.conf

set -g @plugin 'craftzdog/tmux-claude-hatch'

# Install `tpm` if needed.
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Run tpm
run -b '~/.tmux/plugins/tpm/tpm'
